### ISSUE TITLE
Broken link? 

### ISSUE THREAD

**Issue by haymond** [tendermint/awesome#7]
I got a broken link when clicking on "[Ecosystem](https://tendermint.com/ecosystem)" at the top. Should it go somewhere else?

**Comment by lovincyrus** [comment]
It could go to https://cosmos.network/ecosystem for now. Or the Ecosystem can be removed from the Essential Links for the time being. Also, `tendermint.com/ecosystem` is not working because we just launched a new https://tendermint.com/ site today. 🚀

**Comment by haymond** [comment]
Your first idea sounds great. The new Tendermint site is 🔥🔥
